---
- hosts: all:!localhost
  remote_user: root
  roles:
    - role: common

- hosts: dns_servers
  remote_user: root
  vars:
    timestamp: "{{ lookup('pipe', 'date +%s') }}"
  vars_files:
    - domains.yml
  roles:
    - role: dns

- hosts: proxy_servers
  remote_user: root
  vars_files:
    - apps.yml
    - users.yml
  roles:
    - role: proxy
    - role: git

- hosts: docker_servers
  remote_user: root
  roles:
    - role: docker

- hosts: mongo_servers
  remote_user: root
  roles:
    - role: mongod
