---

- hosts: droplets
  remote_user: root
  roles:
  - role: common

- hosts: dns_servers
  remote_user: root
  roles:
  - role: dns

- hosts: cdn_servers
  remote_user: root
  roles:
  - role: cdn

- hosts: mongo_servers
  remote_user: root
  roles:
  - role: mongod

- hosts: docker_servers
  remote_user: root
  roles:
  - role: docker
