---

- name: update apt cache if needed
  apt: update_cache=yes cache_valid_time=3600

- name: install package
  apt: pkg={{ item }} state=latest
  with_items:
    - pound
    - varnish

- name: create varnish configuration file
  template: src=varnish dest=/etc/default/varnish
  notify:
    - restart varnish

- name: create varnish VCL file
  template: src=default.vcl dest=/etc/varnish/default.vcl
  notify:
    - restart varnish

- name: allow ports on firewall
  ufw: rule=allow port={{ item }}
  with_items:
    - 80
    - 443
