---

- name: update apt cache if needed
  apt: update_cache=yes cache_valid_time=3600

- name: install powerdns package
  apt: name=pdns-server state=present

- name: allow dns port on firewall
  action: shell ufw allow 53
