---

- name: install apt-transport-https package
  apt: name=apt-transport-https state=present

- name: add docker apt key
  apt_key: keyserver=keyserver.ubuntu.com id=A88D21E9 state=present

- name: add docker repository
  apt_repository: repo='deb https://get.docker.io/ubuntu docker main' state=present

- name: update apt cache if needed
  apt: update_cache=yes cache_valid_time=3600

- name: install docker package
  apt: name=lxc-docker state=present

- name: enable forwarding traffic
  lineinfile: >
    dest=/etc/default/ufw
    regexp=DEFAULT_FORWARD_POLICY=
    line=DEFAULT_FORWARD_POLICY="ACCEPT"

- name: start docker
  action: service name=docker state=started

- name: ensure pip is installed
  apt: name=python-pip state=present

- name: install fig
  pip: name=fig

- name: create www directory
  file: path=/srv/www/ state=directory owner=git

- name: create www subdirectories
  file: path=/srv/www/{{ item.id }} state=directory owner=git
  with_items: websites

- name: create fig config files
  template: src=fig.yml.j2 dest=/srv/www/{{ item.id }}/fig.yml
  with_items: websites
